-- The debug trace: /pal debug and the checkbox, and what the detection reports.

local function traced(client, text)
    return client:printedContains("[debug]|r " .. text)
end

test("/pal debug switches the trace and is saved", function()
    local client = NewClient():login()
    eq(Saved().debug, false)
    client:slash("debug")
    eq(Saved().debug, true)
    ok(client:printedContains("Debug on."))
    client:slash("debug")
    eq(Saved().debug, false)
    ok(client:printedContains("Debug off."))
end)

test("without debug nothing is traced", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(#client.printed, 0)
end)

test("a shown learn is traced from chat line to splash", function()
    local client = NewClient({ savedDB = { debug = true } }):login()
    client:chat(client:learnLine(SpellLink(16828, "Claw")))
    client:advance(0.3)
    ok(traced(client, "chat: You have learned a new ability: ||cff71d5ff||Hspell:16828"), "links escaped")
    ok(traced(client, "learned: Claw, rank nil, spell 16828"))
    ok(traced(client, "splash: Claw, rank Rank 2"))
end)

test("every reason to skip a learn is traced", function()
    local client = NewClient({ savedDB = { debug = true } }):login(false)
    client:chat(client:learnLine("Claw (Rank 2)"))
    ok(traced(client, "ignored: still in the login wait"))
    client:advance(5)
    client:fire("TRAINER_SHOW")
    ok(traced(client, "trainer window open"))
    client:chat(client:learnLine("Claw (Rank 2)"))
    ok(traced(client, "ignored: a trainer window is open"))
    client:fire("TRAINER_CLOSED")
    ok(traced(client, "trainer window closed"))
    client:chat(client:learnLine("Growl (Rank 2)"))
    ok(traced(client, "ignored: Growl is not a pet ability learned in the wild"))
    client:chat(client:learnLine("Claw"))
    client:fire("LEARNED_SPELL_IN_TAB", 16828)
    ok(traced(client, "LEARNED_SPELL_IN_TAB: spell 16828"))
    ok(traced(client, "merged into the pending Claw"))
    client:advance(0.3)
    client:fire("LEARNED_SPELL_IN_SKILL_LINE", 16828)
    ok(traced(client, "ignored: Claw was shown less than 5 seconds ago"))
end)

test("the debug checkbox follows the setting and writes it", function()
    for _, old in ipairs({ false, true }) do
        local client = NewClient({ oldCheckButton = old }):login()
        local box = client.ns.DebugBox
        local label = box.Text or box.text
        eq(label.text, "Debug trace")
        client:slash("debug")
        client.ns.OptionsPanel.scripts.OnShow(client.ns.OptionsPanel)
        eq(box.checked, true, "synced on show")
        box:SetChecked(false)
        box.scripts.OnClick(box)
        eq(Saved().debug, false)
        box:SetChecked(true)
        box.scripts.OnClick(box)
        eq(Saved().debug, true, "a 1 from GetChecked is saved as true")
    end
end)
