-- Detecting that the hunter learned a pet ability from a beast.

test("a learn line for a wild ability shows the splash with name, rank, icon and pet", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Claw (Rank 2)"))
    eq(client:splashName(), nil, "merged for a moment first")
    client:advance(0.3)
    eq(client:splashName(), "Claw")
    eq(client.splash.Rank.text, "Rank 2")
    eq(client.splash.Icon.texture, 132140)
    eq(client.splash.Source.text, "Nightstalker has taught you Claw.")
    eq(#client.sounds, 1)
end)

test("a renamed pet is named as it is called now", function()
    local client = NewClient():login()
    client.pet.name = "Fluffy"
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(client.splash.Source.text, "Fluffy has taught you Claw.")
    eq(client.splash.Portrait.texture, "portrait:pet:Fluffy")
end)

test("the 'new spell' line counts too", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Bite (Rank 1)", "spell"))
    client:advance(0.3)
    eq(client:splashName(), "Bite")
end)

test("a spell link in the line is unwrapped and its ID supplies rank and icon", function()
    local client = NewClient():login()
    client.pet = nil
    client:chat(client:learnLine(SpellLink(17253, "Bite")))
    client:advance(0.3)
    eq(client:splashName(), "Bite")
    eq(client.splash.Rank.text, "Rank 1")
    eq(client.splash.Icon.texture, 132278)
    eq(client.splash.Source.text, "Teach it to your pet from the Beast Training window.", "no pet, no source")
end)

test("without a rank in the line, the pet's spellbook supplies it", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Claw"))
    client:advance(0.3)
    eq(client.splash.Rank.text, "Rank 2")
end)

test("a name the client cannot texture falls back to the Beast Training icon", function()
    local client = NewClient({ oldSpellAPI = true, noTextureAPI = true }):login()
    client.pet = nil
    client:chat(client:learnLine("Web (Rank 1)"))
    client:advance(0.3)
    eq(client:splashName(), "Web")
    eq(client.splash.Icon.texture, "Interface\\Icons\\Ability_Hunter_BeastTraining")
end)

test("a name with only an icon by name gets that icon", function()
    local client = NewClient():login()
    client.pet = nil
    client:chat(client:learnLine("Demoralizing Screech (Rank 1)"))
    client:advance(0.3)
    eq(client.splash.Icon.texture, 132182)
end)

test("trainer abilities and ordinary spells do not splash", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Growl (Rank 2)"))
    client:chat(client:learnLine("Execute (Rank 1)"))
    client:chat("You feel rested.")
    client:advance(1)
    eq(client:splashName(), nil)
end)

test("nothing counts in the first seconds after login", function()
    local client = NewClient():login(false)
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(4)
    eq(client:splashName(), nil)
    client:advance(1)
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(client:splashName(), "Claw")
end)

test("nothing counts while a trainer window is open", function()
    local client = NewClient():login()
    client:fire("TRAINER_SHOW")
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(1)
    eq(client:splashName(), nil)
    client:fire("TRAINER_CLOSED")
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(client:splashName(), "Claw")
end)

test("the chat line and the spellbook event make one splash, merged", function()
    local client = NewClient():login()
    client.pet = nil
    client:chat(client:learnLine("Claw"))
    client:fire("LEARNED_SPELL_IN_TAB", 16828)
    client:advance(0.3)
    eq(client:splashName(), "Claw")
    eq(client.splash.Rank.text, "Rank 2", "rank from the event")
    eq(client.splash.Icon.texture, 132140, "icon from the event")
    eq(#client.sounds, 1)
    client:fire("LEARNED_SPELL_IN_SKILL_LINE", 16828)
    client:advance(0.3)
    eq(#client.sounds, 1, "a late duplicate is dropped")
    client:advance(5)
    client.ns.HideSplash()
    client:fire("LEARNED_SPELL_IN_SKILL_LINE", 16828)
    client:advance(0.3)
    eq(#client.sounds, 2, "after the window it counts again")
end)

test("a second ability learned while one is pending ends the merge; both show in turn", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:chat(client:learnLine("Bite (Rank 1)"))
    eq(client:splashName(), "Claw", "shown at once")
    client:advance(0.3)
    eq(client:splashName(), "Claw", "Bite waits in the queue")
    client:animate(10)
    eq(client:splashName(), "Bite", "and follows when Claw has faded")
    client:animate(10)
    eq(client:splashName(), nil)
end)

test("secret, empty and non-text chat is ignored", function()
    local client = NewClient():login()
    local line = client:learnLine("Claw (Rank 2)")
    client.secret = line
    client:chat(line)
    client:chat("")
    client:chat(nil)
    client:fire("LEARNED_SPELL_IN_TAB", 999999)
    client:advance(1)
    eq(client:splashName(), nil)
end)

test("a name of only a rank in parentheses keeps the whole text", function()
    local client = NewClient():login()
    client:chat(client:learnLine("(Rank 2)"))
    client:advance(1)
    eq(client:splashName(), nil)
end)

test("a German client: names, rank word and learn line come from the client", function()
    local client = NewClient({ locale = "deDE" }):login()
    client:chat(client:learnLine("Klaue (Rang 2)"))
    client:advance(0.3)
    eq(client:splashName(), "Klaue")
    eq(client.splash.Rank.text, "Rang 2")
    client:chat(client:learnLine("Knurren (Rang 2)"))
    client:advance(1)
    eq(client:splashName(), "Klaue", "Growl is a trainer ability in German too")
end)

test("spell names that are not readable yet are looked up again later", function()
    local client = NewClient():login()
    local getName = C_Spell.GetSpellName
    C_Spell.GetSpellName = function()
        return nil
    end
    client:chat(client:learnLine("Bite (Rank 1)"))
    client:advance(1)
    eq(client:splashName(), nil)
    C_Spell.GetSpellName = getName
    client:chat(client:learnLine("Bite (Rank 1)"))
    client:advance(0.3)
    eq(client:splashName(), "Bite")
end)

test("other classes do not listen at all", function()
    local client = NewClient({ class = "WARRIOR" }):login()
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(1)
    eq(client:splashName(), nil)
end)

test("an event the client lacks does not stop the others", function()
    local client = NewClient({
        knownEvents = { PLAYER_LOGIN = true, PLAYER_LOGOUT = true, ADDON_LOADED = true, CHAT_MSG_SYSTEM = true },
    })
    client:login()
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(client:splashName(), "Claw")
end)

test("a client without learn strings never matches a line", function()
    local client = NewClient({ noLearnStrings = true }):login()
    client:chat("You have learned a new ability: Claw (Rank 2).")
    client:advance(1)
    eq(client:splashName(), nil)
end)
