-- The splash: its animation, hold on hover, closing, moving and settings.

local function showClaw(client)
    client.ns.ShowSplash({ name = "Claw", rank = "Rank 2", icon = 132140 })
    return client
end

test("the splash fades in, stays for the duration, then fades out and hides", function()
    local client = showClaw(NewClient():login())
    eq(client.splash.alpha, 1)
    client:animate(0.5)
    ok(client.splash.shown)
    client:animate(5.6)
    ok(client.splash.shown, "still up just before the duration")
    client:animate(0.3)
    ok(client.splash.alpha < 1, "fading")
    client:animate(1)
    eq(client.splash.shown, false)
end)

test("hovering holds the splash; leaving lets it fade", function()
    local client = showClaw(NewClient():login())
    client.mouseOver = true
    client:animate(20)
    ok(client.splash.shown)
    eq(client.splash.alpha, 1)
    client.mouseOver = false
    client:animate(2)
    eq(client.splash.shown, false)
end)

test("right-click closes it; other clicks do not", function()
    local client = showClaw(NewClient():login())
    client.splash.scripts.OnMouseUp(client.splash, "LeftButton")
    ok(client.splash.shown)
    client.splash.scripts.OnMouseUp(client.splash, "RightButton")
    eq(client.splash.shown, false)
    eq(client.splash.scripts.OnUpdate, nil)
end)

test("dragging moves it and the spot is remembered", function()
    local client = showClaw(NewClient():login())
    eq(client.splash.points[1][1], "CENTER", "default spot")
    client.splash.scripts.OnDragStart(client.splash)
    client.splash.scripts.OnDragStop(client.splash)
    eq(Saved().pos[1], "TOPLEFT")
    eq(Saved().pos[3], 300)
    client.ns.HideSplash()
    client.splash:ClearAllPoints()
    showClaw(client)
    eq(client.splash.points[1][1], "TOPLEFT", "the next splash opens at the saved spot")
    eq(client.splash.points[1][4], 300)
end)

test("scale, sound and a missing name or rank", function()
    local client = NewClient({ savedDB = { scale = 1.5, sound = "off" } }):login()
    client.ns.ShowSplash({})
    eq(client.splash.scale, 1.5)
    eq(#client.sounds, 0)
    eq(client.splash.Name.text, "?")
    eq(client.splash.Rank.text, "")
end)

test("before the settings load, the defaults apply", function()
    local client = NewClient()
    showClaw(client)
    eq(client.splash.scale, 1)
    eq(#client.sounds, 1)
end)

test("a learn from the pet out plays its family's sound", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(client.sounds[1].file, 562387, "the cat's aggro sound")
    eq(client.sounds[1].channel, "Master")
end)

test("a family without its own sound, or a learn not from the pet out, plays level-up", function()
    local client = NewClient():login()
    client.pet.familyID = 20 -- Scorpid
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(client.sounds[1].id, 888)

    client = NewClient():login()
    client:chat(client:learnLine("Bite (Rank 1)"))
    client:advance(0.3)
    eq(client.sounds[1].id, 888, "Nightstalker has no Bite, so its family is not the one that taught it")
end)

test("the levelup and off sound settings", function()
    local client = NewClient({ savedDB = { sound = "levelup" } }):login():slash("test")
    eq(client.sounds[1].id, 888, "level-up even for a cat")
    client = NewClient({ savedDB = { sound = "off" } }):login():slash("test")
    eq(#client.sounds, 0)
end)

test("/pal test plays the family sound of the pet out, or level-up without one", function()
    local client = NewClient():login():slash("test")
    eq(client.sounds[1].file, 562387)
    client.ns.HideSplash()
    client.pet = nil
    client:slash("test")
    eq(client.sounds[2].id, 888)
end)

test("the splash stays as long as the duration setting says", function()
    local client = NewClient({ savedDB = { duration = 2 } }):login()
    showClaw(client)
    client:animate(1.9)
    ok(client.splash.shown)
    client:animate(1)
    eq(client.splash.shown, false)
end)

test("a learn from the pet out shows its portrait as a badge", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Claw (Rank 2)"))
    client:advance(0.3)
    eq(client.splash.Portrait.shown, true)
    eq(client.splash.Portrait.texture, "portrait:pet:Nightstalker")
end)

test("no portrait without a pet, or when the pet out does not have the ability", function()
    local client = NewClient():login()
    client:chat(client:learnLine("Bite (Rank 1)"))
    client:advance(0.3)
    eq(client:splashName(), "Bite")
    eq(client.splash.Portrait.shown, false, "Nightstalker has no Bite: it came from another pet")

    client.pet = nil
    client.ns.ShowSplash({ name = "Claw", petPortrait = true })
    eq(client.splash.Portrait.shown, false, "no pet out")
end)

test("a client without SetPortraitTexture shows no portrait", function()
    local client = NewClient({ noPortraitAPI = true }):login()
    client:slash("test")
    eq(client.splash.Portrait.shown, false)
end)

test("/pal test shows the portrait when a pet is out", function()
    local client = NewClient():login():slash("test")
    eq(client.splash.Portrait.texture, "portrait:pet:Nightstalker")
    eq(client.splash.Portrait.shown, true)
end)

test("a client without mask textures still builds the splash", function()
    local client = NewClient({ noMasks = true }):login()
    showClaw(client)
    ok(client.splash.shown)
end)
